### ISSUE TITLE
Vanity Does not work with optifine and optifabric

### ISSUE THREAD

**Issue by Enikimm** [AllyTally/VanitySlots#3]
I would like to use optifine and optifabric witht his mod but it does not work. can you please work on making it compatible.

**Comment by NyakoFox** [comment]
Optifine will not be supported, there are many alternatives on Fabric/Quilt that you can use, such as Sodium, Lithium and Starlight (or Phosphor), Zoomify for zooming, Iris for shaders, etc etc. Please try to move off of Optifine since it just causes headaches for developers.
